version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB__NAME:-vault}
      POSTGRES_USER: ${DB__USER:-vault}
      POSTGRES_PASSWORD: ${DB__PASS:?database password required}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: vaultwarden/server:${VAULT__TAG:-latest}
    restart: unless-stopped
    ports:
      - "${VAULT__PORT_HTTP:-9011}:80"
      - "${VAULT__PORT_WS:-9012}:3012"
    environment:
      DATABASE_URL: postgresql://${DB__USER:-vault}:${DB__PASS}@postgres:5432/${DB__NAME:-vault}
      ADMIN_TOKEN: ${VAULT__ADMIN_TOKEN:?admin token required}
    env_file:
      - .env
    volumes:
      - ./data/server:/data
    depends_on:
      - db

  pgbackups:
    image: prodrigestivill/postgres-backup-local:latest
    restart: unless-stopped
    # user: postgres:postgres # TODO: Possibly enable this in the future
    volumes:
        - ./data/db-backups:/backups
    depends_on:
        - postgres
    environment:
        POSTGRES_HOST: postgres
        POSTGRES_DB: ${DB__NAME:-vault}
        POSTGRES_USER: ${DB__USER:-vault}
        POSTGRES_PASSWORD: ${DB__PASS}
        SCHEDULE: ${DB__BACKUP_SCHEDULE:-@daily}
        BACKUP_KEEP_DAYS: ${DB__BACKUP_KEEP_DAYS:-7}
        BACKUP_KEEP_WEEKS: ${DB__BACKUP_KEEP_WEEKS:-1}
        BACKUP_KEEP_MONTHS: ${DB__BACKUP_KEEP_MONTHS:-0}
        HEALTHCHECK_PORT: 8080

volumes:
  database:
    driver: local
